run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - gosimple
    - govet
    - misspell
    - staticcheck
    - unused

issues:
  exclude-use-default: false

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
